### ISSUE TITLE
Add simple wrapper for work with MongoDB 

### ISSUE THREAD

**Issue by AKorpusenko** [GolosChain/Qa#23]
As in Golos was added support of MongoDB, which provides more flexible access to the data, we need to provide tools for golos-test to check correct work of features connected with Mongo.

**Comment by maslenitsa93** [comment]
I am agree. Some checklists contain instructions like "In Mongo: check foo value". https://mongodb.github.io/node-mongodb-native/ could be used for it.
But cli_wallet support is more important.

**Comment by maslenitsa93** [comment]
https://mongodb.github.io/node-mongodb-native/ could be used for it.
But it is simpler to just call mongo utility.
Example to drop DB:
```
mongo --host 172.17.0.1
use Golos
db.dropDatabase()
Ctrl+C
```
and same utility for all another purposes...
