### ISSUE TITLE
check the veracity of the docks.

### ISSUE THREAD

**Issue by kotbegemot** [GolosChain/Qa#7]
- [x] 1. To collect Docker container with the test net .
- [x] 2. Run Docker container with test net.
- [x] 3. Get out of the running container to pick up the wallet .
- [x] 4. set a password on your wallet.
- [x] 5. To obtain information about the user cyberfounder .
- [x] 6. Document actions taken.

[Wiki](https://github.com/GolosChain/golos/wiki/Build-instruction)

**Comment by BaroH4er** [comment]
**Done**

```
# git clone https://github.com/GolosChain/golos.git -b golos-v0.18.0
# cd golos/
# git submodule update --init --recursive -f
# docker build -t goloschain/golos -f share/golosd/docker/Dockerfile-testnet .
# docker run -d -p 4243:4243 -p 8090:8090 -p 8091:8091 --name golos-default goloschain/golos
# docker exec -ti golos-default /usr/local/bin/cli_wallet --server-rpc-endpoint="ws://127.0.0.1:8091"
> set_password 1qaz
> unlock 1qaz
> import_key 5JVFFWRLwz6JoP9kguuRFfytToGU6cLgBVTL9t6NB3D3BQLbUBS
> info
```
![image](https://user-images.githubusercontent.com/21989598/40919400-11d8bf92-6812-11e8-86ce-6474cea0596b.png)
